-- Knitting Catalog schema
-- Run against an existing (empty) database, e.g.:
--   psql -U postgres -d knitting_catalog -f db/schema.sql

CREATE TABLE IF NOT EXISTS catalogo (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(150)   NOT NULL,
    categoria      VARCHAR(100)   NOT NULL,
    fabricante     VARCHAR(150)   NOT NULL,
    precio         NUMERIC(10,2)  NOT NULL,
    unidad_precio  VARCHAR(20)    NOT NULL,
    imagen         TEXT,
    descripcion    TEXT
);
